routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PersonController@index')->name('index');
Route::get('create', 'PersonController@create')->name('create');
Route::post('store', 'PersonController@store')->name('store');
Route::get('show/{person}', 'PersonController@show')->name('show');
Route::get('edit/{person}', 'PersonController@edit')->name('edit');
Route::put('update/{person}', 'PersonController@update')->name('update');
Route::delete('delete/{person}', 'PersonController@destroy')->name('destroy');

Route::resource('ticket', 'TicketController');

app/Person.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Person extends Model
{
    public function ticket(){
        return $this->hasOne(Ticket::class); //or use "App\Ticket" class
    }
}

app/Ticket.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Ticket extends Model
{
    public function person(){
        return $this->belongsTo('App\Person');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PersonController.php
<?php

namespace App\Http\Controllers;

use App\Person;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class PersonController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $persons = Person::latest()->get();
        return view('welcome', compact('persons'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('insert');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Validator::make($request->all(), [
            'name' => 'required|unique:persons|string'
        ])->validate();
        $person = new Person();
        $person->name = $request->name;
        $person->save();
        Toastr::success('Person Successfully Saved :)', 'Success');
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $person = Person::findOrFail($id);
        return view('show', compact('person'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $person = Person::findOrFail($id);
        return view('edit', compact('person'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Validator::make($request->all(), [
            'name' => 'required|unique:persons|string'
        ])->validate();
        $person = Person::findOrFail($id);
        $person->name = $request->name;
        $person->save();
        Toastr::success('Person Successfully Updated :)', 'Success');
        return redirect(route('index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $person = Person::findOrFail($id);
        $person->delete();
        Toastr::success('Person Successfully Deleted :)', 'Success');
        return back();
    }
}

app/Http/Controllers/TicketController.php
<?php

namespace App\Http\Controllers;

use App\Person;
use App\Ticket;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class TicketController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tickets = Ticket::latest()->get();
        return view('ticket.index', compact('tickets'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $persons = Person::all();
        return view('ticket.insert', compact('persons'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Validator::make($request->all(), [
            'ticket' => 'string|required',
            'person' => 'required'
        ])->validate();

        $ticket = new Ticket();
        $ticket->movie_ticket_id = $request->ticket;
        $ticket->person_id = $request->person;
        $ticket->save();
        Toastr::success('Ticket Successfully Saved :)', 'Success');
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $ticket = Ticket::findOrFail($id);
        return view('ticket.show', compact('ticket'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $ticket = Ticket::findOrFail($id);
        $persons = Person::all();
        return view('ticket.edit', compact('ticket', 'persons'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Validator::make($request->all(), [
            'ticket' => 'string|required',
            'person' => 'required'
        ])->validate();

        $ticket = Ticket::findOrFail($id);
        $ticket->movie_ticket_id = $request->ticket;
        $ticket->person_id = $request->person;
        $ticket->save();
        Toastr::success('Ticket Successfully Updated :)', 'Success');
        return redirect(route('ticket.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $ticket = Ticket::findOrFail($id);
        $ticket->delete();
        Toastr::success('Ticket Successfully Deleted :)', 'Success');
        return back();
    }
}

resources/views/edit.blade.php
@extends('layouts.app')

@section('site-title', 'One to One RelationShip')


@section('header-title', 'ONE TO ONE RELATIONSHIP')


@section('main-content')
    <div class="card">
        <div class="card-header bg-secondary">
            <h3 class="card-title">Insert Data</h3>
            <a href="{{ route('index') }}" class="btn btn-primary float-right" style="margin-top: -40px;">Back</a>
        </div>
        <div class="card-body">
            <form action="{{ route('update', $person->id) }}" method="post">
                @csrf
                @method("PUT")
                <div class="form-group row">
                    <label for="name" class="col-sm-2 col-form-label">Name</label>
                    <div class="col-sm-10">
                        <input type="text" name="name" class="form-control" id="name" placeholder="Name" value="{{ $person->name }}">
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
                <form/>
        </div>
    </div>
@endsection

resources/views/insert.blade.php
@extends('layouts.app')

@section('site-title', 'One to One RelationShip')


@section('header-title', 'ONE TO ONE RELATIONSHIP')


@section('main-content')
    <div class="card">
        <div class="card-header bg-secondary">
            <h3 class="card-title">Insert Data</h3>
            <a href="{{ route('index') }}" class="btn btn-primary float-right" style="margin-top: -40px;">Back</a>
        </div>
        <div class="card-body">
            <form action="{{ route('store') }}" method="post">
                @csrf
                <div class="form-group row">
                    <label for="name" class="col-sm-2 col-form-label">Name</label>
                    <div class="col-sm-10">
                        <input type="text" name="name" class="form-control" id="name" value="{{ old('name') }}" placeholder="Name">
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
            <form/>
        </div>
    </div>
@endsection

resources/views/layouts/app.blade.php
@include('layouts.partials.header')

<div class="container mt-5">
    <div class="row">
        <div class="col-md-12">
            @yield('main-content')
        </div>
    </div>
</div>


@include('layouts.partials.footer')

resources/views/layouts/partials/footer.blade.php
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-footer" style="position: fixed;bottom: 0;">
                    &copy; {{ now()->year }} MI SHAJIB. ALL RIGHTS RESERVED.
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<!-- Sweet Alert 2 -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@8.3.0/dist/sweetalert2.all.min.js"></script>
<!-- Sweet Alert 2 End -->
<!-- Toastr Js -->
<script src="http://cdn.bootcss.com/jquery/2.2.4/jquery.min.js"></script>
<script src="https://cdn.bootcss.com/toastr.js/latest/js/toastr.min.js"></script>
{!! Toastr::message() !!}
<!-- Toastr Js End -->
<script>
    @if($errors->any())
    @foreach($errors->all() as $error)
    toastr.error('{{ $error }}', 'Error', {
        closeButton: true,
        progressBar: true,
    });
    @endforeach
    @endif
</script>
@stack('js')

</body>
</html>

resources/views/layouts/partials/header.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@yield('site-title', 'Enter title here')</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <!-- Toastr Css -->
    <link rel="stylesheet" href="https://cdn.bootcss.com/toastr.js/latest/css/toastr.min.css">
    <!-- Toastr Css End -->
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card bg-primary text-center mt-2">
                <div class="card-header">
                    <h2 class="card-title">
                        @yield('header-title', 'Enter Header Title Here')
                    </h2>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/show.blade.php
@extends('layouts.app')

@section('site-title', 'One to One RelationShip')


@section('header-title', 'ONE TO ONE RELATIONSHIP')


@section('main-content')
    <div class="card">
        <div class="card-header bg-secondary">
            <h3 class="card-title">Show Data</h3>
            <a href="{{ route('index') }}" class="btn btn-primary float-right" style="margin-top: -40px;">Back</a>
        </div>
        <div class="card-body">
            @if (!empty($person))
                <h1>Name: {{ $person->name }}</h1>
            @else
                <h1>Name: No data found!</h1>
            @endif

            @if (!empty($person->ticket))
               <h3>Ticket ID: {{ $person->ticket->movie_ticket_id }}</h3>
            @else
                <h3>Ticket ID: No data found!</h3>
            @endif

            <a href="{{ route('edit', $person->id) }}" class="btn btn-primary">Edit</a>
        </div>
    </div>
@endsection

resources/views/ticket/edit.blade.php
@extends('layouts.app')

@section('site-title', 'One to One RelationShip')


@section('header-title', 'ONE TO ONE RELATIONSHIP')


@section('main-content')
    <div class="card">
        <div class="card-header bg-secondary">
            <h3 class="card-title">Insert Data</h3>
            <a href="{{ route('ticket.index') }}" class="btn btn-primary float-right" style="margin-top: -40px;">Back</a>
        </div>
        <div class="card-body">
            <form action="{{ route('ticket.update', $ticket->id) }}" method="post">
                @csrf
                @method('PUT')
                <div class="form-group row">
                    <label for="ticket" class="col-sm-2 col-form-label">Movie Ticket</label>
                    <div class="col-sm-10">
                        <input type="text" name="ticket" class="form-control" id="ticket" value="{{ $ticket->movie_ticket_id }}" placeholder="Ticket">
                    </div>
                </div>

                <div class="form-group row">
                    <label for="person" class="col-sm-2 col-form-label">Person</label>
                    <div class="col-sm-10">
                        <select name="person" id="person" class="custom-select my-1 mr-sm-2">
                            <option selected disabled>Choose...</option>
                            @if (!empty($persons))
                                @foreach($persons as $person)
                                    <option {{ $ticket->person_id == $person->id ? 'selected':'' }} value="{{ $person->id }}">{{ $person->name }}</option>
                                @endforeach
                            @else
                                <option disabled>No data found!!</option>
                            @endif
                        </select>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
                <form/>
        </div>
    </div>
@endsection

resources/views/ticket/index.blade.php
@extends('layouts.app')

@section('site-title', 'One to One RelationShip')


@section('header-title', 'ONE TO ONE RELATIONSHIP')


@section('main-content')
    <div class="card">
        <div class="card-header bg-secondary">
            <h3 class="card-title">View All Ticket</h3>
            <a href="{{ route('ticket.create') }}" class="btn btn-primary float-right" style="margin-top: -40px;">Add New</a>
            <a href="{{ route('index') }}" class="btn btn-primary float-right" style="margin-top: -40px; margin-right: 100px;">Back</a>
        </div>
        <div class="card-body">
            <table class="table table-bordered table-dark text-center">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Action</th>
                </tr>
                </thead>
                <tbody>
                    @if (!empty($tickets))
                        @foreach($tickets as $key=>$ticket)
                            <tr>
                                <td>{{ ++$key }}</td>
                                <td>{{ $ticket->movie_ticket_id }}</td>
                                <td>
                                    <a href="{{ route('ticket.edit', $ticket->id) }}" class="btn btn-info btn-sm">
                                        <i class="fa fa-edit"></i>
                                    </a>

                                    <button onclick="deleteTicket({{ $ticket->id }})" class="btn btn-danger" type="button">
                                        <i class="fa fa-trash"></i>
                                    </button>
                                    <form id="delete-form-{{ $ticket->id }}" action="{{ route('ticket.destroy', $ticket->id) }}" method="POST" style="display: none;">
                                        @csrf
                                        @method('DELETE')
                                    </form>

                                    <a href="{{ route('ticket.show', $ticket->id) }}" class="btn btn-primary btn-sm">
                                        <i class="fa fa-eye"></i>
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="3">No data found!!</td>
                        </tr>
                    @endif

                </tbody>
            </table>
        </div>
    </div>
@endsection

@push('js')
    <script>
        function deleteTicket(id) {
            const swalWithBootstrapButtons = Swal.mixin({
                customClass: {
                    confirmButton: 'btn btn-success',
                    cancelButton: 'btn btn-danger'
                },
                buttonsStyling: false,
            })

            swalWithBootstrapButtons.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonText: 'Yes, delete it!',
                cancelButtonText: 'No, cancel!',
                reverseButtons: true
            }).then((result) => {
                if (result.value) {
                    event.preventDefault();
                    document.getElementById('delete-form-'+id).submit();
                } else if (
                    // Read more about handling dismissals
                    result.dismiss === Swal.DismissReason.cancel
                ) {
                    swalWithBootstrapButtons.fire(
                        'Cancelled',
                        'Your data is safe :)',
                        'error'
                    )
                }
            })
        }
    </script>
@endpush

resources/views/ticket/insert.blade.php
@extends('layouts.app')

@section('site-title', 'One to One RelationShip')


@section('header-title', 'ONE TO ONE RELATIONSHIP')


@section('main-content')
    <div class="card">
        <div class="card-header bg-secondary">
            <h3 class="card-title">Insert Data</h3>
            <a href="{{ route('ticket.index') }}" class="btn btn-primary float-right" style="margin-top: -40px;">Back</a>
        </div>
        <div class="card-body">
            <form action="{{ route('ticket.store') }}" method="post">
                @csrf
                <div class="form-group row">
                    <label for="ticket" class="col-sm-2 col-form-label">Movie Ticket</label>
                    <div class="col-sm-10">
                        <input type="text" name="ticket" class="form-control" id="ticket" value="{{ old('ticket') }}" placeholder="Ticket">
                    </div>
                </div>

                <div class="form-group row">
                    <label for="person" class="col-sm-2 col-form-label">Person</label>
                    <div class="col-sm-10">
                        <select name="person" id="person" class="custom-select my-1 mr-sm-2">
                            <option selected disabled>Choose...</option>
                            @if (!empty($persons))
                                @foreach($persons as $person)
                                    <option value="{{ $person->id }}">{{ $person->name }}</option>
                                @endforeach
                            @else
                                <option disabled>No data found!!</option>
                            @endif
                        </select>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
            <form/>
        </div>
    </div>
@endsection

resources/views/ticket/show.blade.php
@extends('layouts.app')

@section('site-title', 'One to One RelationShip')


@section('header-title', 'ONE TO ONE RELATIONSHIP')


@section('main-content')
    <div class="card">
        <div class="card-header bg-secondary">
            <h3 class="card-title">Show Data</h3>
            <a href="{{ route('ticket.index') }}" class="btn btn-primary float-right" style="margin-top: -40px;">Back</a>
        </div>
        <div class="card-body">
            <h1>Ticket: {{ $ticket->movie_ticket_id }}</h1>
            <h3>Person Name: {{ $ticket->person->name }}</h3>
            <a href="{{ route('ticket.edit', $ticket->id) }}" class="btn btn-primary">Edit</a>
        </div>
    </div>
@endsection